project_id = "wnrbxwzeshgblkfidayb"

[functions."escrow-release"]
verify_jwt = false

[functions."stripe-webhook"]
verify_jwt = false

# Email Templates Configuration
[auth.email.template.confirmation]
subject = "Confirmă-ți contul GearUp"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.invite]
subject = "Ai fost invitat să te alături GearUp"
content_path = "./supabase/templates/invite.html"

[auth.email.template.recovery]
subject = "Resetează-ți parola GearUp"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Link de conectare GearUp"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirmă schimbarea email-ului GearUp"
content_path = "./supabase/templates/email_change.html"

[auth.email.template.reauthentication]
subject = "Confirmă reautentificarea GearUp"
content_path = "./supabase/templates/reauthentication.html"