// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnrbxwzeshgblkfidayb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InducmJ4d3plc2hnYmxrZmlkYXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDE3OTUsImV4cCI6MjA2Njg3Nzc5NX0.CxA3sPogy9ZhQ3f1pQP6n0_fcb73Fs8H0XtCw9W4BNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});